### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by CoderHar** [codesinghanoop/react-native-d3-tree-graph#2]
im getting this issue when i use the same code in the documentation

**Comment by codesinghanoop** [comment]
@CoderHar please use the code in the example. I think you are missing x coordinate data. Let me know if you face the problem.

**Comment by codesinghanoop** [comment]
@CoderHar use the below dummy data.

var root = {
    name: "",
    id: 1,
    hidden: true,
    children: [ {
            name: "Q",
            id: 16,
            no_parent: true
        },
        {
        name: "",
        id: 2,
        no_parent: true,
        hidden: true,
        children: [{
            name: "J",
            id: 12,

        }, {
            name: "L",
            id: 13,
            no_parent: true
        }, {
            name: "C",
            id: 3
        }, {
            name: "",
            id: 4,
            hidden: true,
            no_parent: true,
            children: [{
                name: "D",
                id: 5,
            }, {
                name: "",
                id: 14,
                hidden: true,
                no_parent: true,
                children: [{
                    name: "P",
                    id: 15,
                }]
            }, {
                name: "E",
                id: 6,
            }]
        }, {
            name: "K",
            id: 11
        }, {
            name: "G",
            id: 7,
            children: [{
                name: "H",
                id: 8,
            }, {
                name: "I",
                id: 9,
            }]
        }]
    }, {
        name: "M",
        id: 10,
        no_parent: true,
        children: [
          
        ]
    },
    {
        name: "anoop",
        id: 155,
        no_parent: true,
        children: [{
            name: "H",
            id: 8,
        }, {
            name: "I",
            id: 9,
        },
        {
            name: "I",
            id: 9,
        },
        {
            name: "I",
            id: 9,
        },
        {
            name: "I",
            id: 9,
        },
        
      ]
    },
    {
            name: "x",
            id: 16,
            no_parent: true
        }
  
  ]
}

var siblings = [{
    source: {
        id: 3,
        name: "C"
    },
    target: {
        id: 11,
        name: "K"
    }
}, {
    source: {
        id: 12,
        name: "L"
    },
    target: {
        id: 13,
        name: "J"
    }
}, {
    source: {
        id: 5,
        name: "D"
    },
    target: {
        id: 6,
        name: "E"
    }
}, {
    source: {
        id: 16,
        name: "Q"
    },
    target: {
        id: 10,
        name: "M"
    }
}];

**Comment by CoderHar** [comment]
@codesinghanoop hello still i get an error ,**error while updating property position X in shadow node of type:RNSVGText 
expected array,got a string **

**Comment by codesinghanoop** [comment]
@CodeHar please use the example not the one in the documentation it’s incomplete.

**Comment by CoderHar** [comment]
yeah i used the code you have given now but i get the error
****error while updating property position X in shadow node of type:RNSVGText ****
expected array,got a string

**Comment by codesinghanoop** [comment]
@CoderHar i think there is some problem with react-native-svg version ,need to check.

In the meanwhile please try the same version of svg in the example project.

**Comment by CoderHar** [comment]
@codesinghanoop hi there, your example project is also no working

**Comment by codesinghanoop** [comment]
@CoderHar will check and get back to you.

**Comment by CoderHar** [comment]
@codesinghanoop now its working

**Comment by codesinghanoop** [comment]
@CoderHar 

sounds good and let me know if you need enhancement. 

Would you like to share how you make it working?
