### ISSUE TITLE
Is it able to show an image for each node?

### ISSUE THREAD

**Issue by suijunqiang** [codesinghanoop/react-native-d3-tree-graph#5]
Hello,
Thanks to your amazing project, but is there any way to show image for each node?

Thanks & Best Regards
Sui

**Comment by codesinghanoop** [comment]
I was working on it from long time will update here once it's done.

**Comment by codesinghanoop** [comment]
Hi sui please update the version and verify if this resolve your problem. 

Thanks

**Comment by suijunqiang** [comment]
Hi, anoop,

It's works well in your new version.
Thanks for your response & support.

Thanks & Best Regards
Sui
