### ISSUE TITLE
Nodes label rendering issue

### ISSUE THREAD

**Issue by atifgk** [codesinghanoop/react-native-d3-tree-graph#9]
Hi,

I have followed example code and able to draw tree base on data. but only images are rendering. i'm not able to see any label. can you please help me regarding this issue? also can i only show label instead of images on nodes? what about node click event? i want to show alert when node get clicked.

Thanks

**Comment by atifgk** [comment]
@codesinghanoop

**Comment by codesinghanoop** [comment]
@atifgk As you can see to the example image, both the image & label are rendered properly. Please can you post your code here? About other feature requested PRs are welcome.

**Comment by kr396** [comment]
Same issue with latest react-native-svg library.

If we use version ^9.5.1 issue resolves.

**Comment by alishayb** [comment]
Hello, 

I have the same problem. I'm using react-native-svg version 12.3.0 but the label isn't rendered, only the image. Is there any solution?

Thanks

**Comment by codesinghanoop** [comment]
Hi @alishayb , thanks for using the library. Please can you use react-native-svg library version `^9.5.1` . I think this will solve your problem. Happy coding

**Comment by codesinghanoop** [comment]
@atifgk feel free to reopen if the issue still exist
